Fligt 199
BenYtt/AirLineAPI-Grupp-G pull request #130
Opened 2020-05-19 08:43 UTC by Irvper77

2020-05-19 16:05 UTC, BenYtt commented on AirLineAPI/Controllers/PassengersController.cs
> +                var result = await _passengerRepo.GetPassengers(timeTable);
Det blir väll samma här att "result == null" är det man ska kolla efter? Är lite oklar men tror det i alla fall

2020-05-20 10:06 UTC, BenYtt requested changes

2020-05-20 10:06 UTC, BenYtt commented on AirLineAPI/Controllers/PassengersController.cs
> +                if (_passengerRepo == null)
Jag förstår inte varför det är samma changes varje gång. Varje commit byts namnet från repo -> _passengerRepo. Ta reda på varför det blir så!

2020-05-20 12:22 UTC, Irvper77 commented on AirLineAPI/Configuration/MappedProfile.cs
> +
skapade passenger map

2020-05-20 12:40 UTC, BenYtt commented
Mergeconflict här med @Irvper77

2020-05-20 13:02 UTC, merged